### ISSUE TITLE
Can't update product!

### ISSUE THREAD

**Issue by kybarg** [kybarg/tb#47]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot use 'in' operator to search for '_id' in { _id: 580
    at Document.$__buildDoc (/app/node_modules/mongoose/lib/document.
    at new Document (/app/node_modules/mongoose/lib/document.js:61:20
    at Document.Subdocument (/app/node_modules/mongoose/lib/types/sub
    at Document._embedded (/app/node_modules/mongoose/lib/schema/embe
    at SchemaType.Embedded.castForQuery (/app/node_modules/mongoose/l
    at Query._castUpdateVal (/app/node_modules/mongoose/lib/query.js:
    at Query._walkUpdatePath (/app/node_modules/mongoose/lib/query.js
    at Query._castUpdate (/app/node_modules/mongoose/lib/query.js:245
    at castDoc (/app/node_modules/mongoose/lib/query.js:2657:18)
    at Query._findAndModify (/app/node_modules/mongoose/lib/query.js:
    at Query._findOneAndUpdate (/app/node_modules/mongoose/lib/query.
    at /app/node_modules/kareem/index.js:239:8
    at /app/node_modules/kareem/index.js:18:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by kybarg** [comment]
closed with #50
